version: '3'

includes:
    claude: .tk/claude/Taskfile.yaml #!tk
    default: .tk/default/Taskfile.yaml #!tk
    dependabot: .tk/dependabot/Taskfile.yaml #!tk
    git: .tk/git/Taskfile.yaml #!tk
    go: .tk/go/Taskfile.yaml #!tk
    golangci: .tk/golangci/Taskfile.yaml #!tk
    goreleaser: .tk/goreleaser/Taskfile.yaml #!tk
    install: .tk/install/Taskfile.yaml #!tk
    license: .tk/license/Taskfile.yaml #!tk
    trufflehog: .tk/trufflehog/Taskfile.yaml #!tk

dotenv:
  - .env
  - PROJECT
  - .env.default
