package powerpacks

import (
	"errors"
	"fmt"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// ErrInlineIncludes is returned when the root Taskfile declares its includes inline
// (`includes: {...}`), which tk cannot merge into without rewriting the user's file.
var ErrInlineIncludes = errors.New("`includes:` must be a block mapping for tk to merge its includes")

const defaultIndent = "    "

var (
	includesKeyRegexp = regexp.MustCompile(`^includes:[ \t]*(#.*)?$`)
	indentRegexp      = regexp.MustCompile(`^[ \t]+`)

	// legacyIncludeRegexp matches an include generated by tk before Marker existed,
	// e.g. `    golangci: .tk/golangci/Taskfile.yaml`.
	legacyIncludeRegexp = regexp.MustCompile(`^[ \t]+([A-Za-z0-9_.-]+):[ \t]*\.?/?\.tk/[^/]+/Taskfile\.ya?ml[ \t]*$`)
)

// MergeTaskfile injects the tk includes into an existing Taskfile, replacing only the
// lines tk owns and leaving every other line byte for byte identical. An empty content
// produces a brand new Taskfile.
func MergeTaskfile(content string, taskfiles map[string]string) (string, error) {
	if strings.TrimSpace(content) == "" {
		return newTaskfile(taskfiles), nil
	}

	lines, ending := splitLines(content)

	start := -1

	for i, line := range lines {
		if !strings.HasPrefix(line, "includes:") {
			continue
		}

		if !includesKeyRegexp.MatchString(line) {
			return "", fmt.Errorf("%w: found %q", ErrInlineIncludes, line)
		}

		start = i

		break
	}

	if start == -1 {
		return appendIncludes(lines, taskfiles, ending), nil
	}

	end := blockEnd(lines, start)
	kept, insert, indent := splitBlock(lines[start+1 : end])

	merged := make([]string, 0, len(kept)+len(taskfiles))
	merged = append(merged, kept[:insert]...)
	merged = append(merged, renderIncludes(taskfiles, indent)...)
	merged = append(merged, kept[insert:]...)

	out := make([]string, 0, len(lines)+len(merged))
	out = append(out, lines[:start+1]...)
	out = append(out, merged...)
	out = append(out, lines[end:]...)

	return joinLines(out, ending), nil
}

// MergeEnvrc makes sure the export tk owns is present, without dropping anything else.
func MergeEnvrc(content string) string {
	export := envrcExport + " " + Marker

	if strings.TrimSpace(content) == "" {
		return joinLines([]string{export}, "\n")
	}

	lines, ending := splitLines(content)

	for i, line := range lines {
		if strings.Contains(line, "TASK_X_REMOTE_TASKFILES") {
			lines[i] = export

			return joinLines(lines, ending)
		}
	}

	return joinLines(append(lines, export), ending)
}

// newTaskfile renders a complete Taskfile, used when the target has none yet.
func newTaskfile(taskfiles map[string]string) string {
	footer, _ := splitLines(taskfileFooter)

	lines := []string{taskfileVersion, "", taskfileHeader}
	lines = append(lines, renderIncludes(taskfiles, defaultIndent)...)
	lines = append(lines, "")
	lines = append(lines, footer...)

	return joinLines(lines, "\n")
}

// appendIncludes adds an includes block to a Taskfile that has none.
func appendIncludes(lines []string, taskfiles map[string]string, ending string) string {
	for len(lines) > 0 && strings.TrimSpace(lines[len(lines)-1]) == "" {
		lines = lines[:len(lines)-1]
	}

	lines = append(lines, "", taskfileHeader)
	lines = append(lines, renderIncludes(taskfiles, defaultIndent)...)

	return joinLines(lines, ending)
}

// blockEnd returns the index of the first line after the includes block, a block ending
// on the next line that is neither empty nor indented.
func blockEnd(lines []string, start int) int {
	for i := start + 1; i < len(lines); i++ {
		if strings.TrimSpace(lines[i]) == "" || indentRegexp.MatchString(lines[i]) {
			continue
		}

		return i
	}

	return len(lines)
}

// splitBlock drops the tk owned lines from an includes block and reports the remaining
// lines, where the new tk includes should go, and the indentation they should use.
func splitBlock(block []string) ([]string, int, string) {
	kept := make([]string, 0, len(block))
	insert := -1
	indent := ""

	for _, line := range block {
		if isTKInclude(line) {
			if insert < 0 {
				insert = len(kept)
				indent = indentRegexp.FindString(line)
			}

			continue
		}

		kept = append(kept, line)
	}

	// Older tk versions left blank lines at the end of the block: keep a single separator.
	trimmed := len(kept)
	for trimmed > 0 && strings.TrimSpace(kept[trimmed-1]) == "" {
		trimmed--
	}

	if trimmed < len(kept) {
		kept = append(kept[:trimmed], "")
	}

	if insert < 0 {
		// No tk include yet: land right after the last include the user wrote.
		insert = trimmed
	}

	if insert > len(kept) {
		insert = len(kept)
	}

	if indent == "" {
		indent = blockIndent(kept)
	}

	return kept, insert, indent
}

// blockIndent picks up the indentation the user already uses for their own includes.
func blockIndent(block []string) string {
	for _, line := range block {
		if strings.TrimSpace(line) == "" {
			continue
		}

		if indent := indentRegexp.FindString(line); indent != "" {
			return indent
		}
	}

	return defaultIndent
}

// renderIncludes renders one marked line per powerpack, sorted for a stable diff.
func renderIncludes(taskfiles map[string]string, indent string) []string {
	names := make([]string, 0, len(taskfiles))
	for name := range taskfiles {
		names = append(names, name)
	}

	sort.Strings(names)

	lines := make([]string, 0, len(names))
	for _, name := range names {
		lines = append(lines, fmt.Sprintf("%s%s: %s %s", indent, name, filepath.ToSlash(taskfiles[name]), Marker))
	}

	return lines
}

// isTKInclude tells whether an include line belongs to tk, either because it carries the
// marker or because it was generated before the marker existed.
func isTKInclude(line string) bool {
	if strings.HasSuffix(strings.TrimRight(line, " \t"), Marker) {
		return true
	}

	matches := legacyIncludeRegexp.FindStringSubmatch(line)

	// `taskfile:` is a key of an expanded include, not an include name.
	return matches != nil && matches[1] != "taskfile"
}

// splitLines splits a file into lines and reports the line ending it uses, so a file
// written on Windows is given back with the endings it came with.
func splitLines(content string) ([]string, string) {
	ending := "\n"
	if strings.Contains(content, "\r\n") {
		ending = "\r\n"
	}

	lines := strings.Split(strings.TrimSuffix(content, "\n"), "\n")
	for i, line := range lines {
		lines[i] = strings.TrimSuffix(line, "\r")
	}

	return lines, ending
}

func joinLines(lines []string, ending string) string {
	return strings.Join(lines, ending) + ending
}
