version: '3'

vars:
  INSTALL_DEFAULT_PATTERN: ".*:install"
  UNINSTALL_DEFAULT_PATTERN: ".*:uninstall"

tasks:
  default:
    - task: install

  install:
    summary: |
      Run install commands in task.

      The following variables are available:

      | VARIABLE       | DESCRIPTION                    | DEFAULT |
      |----------------|--------------------------------|---------|
      | `PATTERN`      | the task name pattern to match | `{{.INSTALL_DEFAULT_PATTERN}}` |

      Examples:
        - `task install` will run all install tasks
        - `task {{.TASK}}` will explicitly run all install tasks
      
      Note:
        You can add any extra to all install commands by using "--". For example `task -- -f` to force all update.
    vars:
      PATTERN: '{{.PATTERN | default .INSTALL_DEFAULT_PATTERN}}'

    # this one-line is pretty scary
    cmds:
      - cmd: task -a --json | jq -c '[ (.tasks[] | select( .name | test({{.PATTERN | quote}})) | select( .name | index({{.TASK | quote}}) | not) ) | .name] | .[]' | xargs -n 1 -L1 -I'{}' sh -c 'task {} {{.CLI_ARGS}} || exit 255'

  uninstall:
    summary: |
      Run install commands in task.

      The following variables are available:

      | VARIABLE       | DESCRIPTION                    | DEFAULT |
      |----------------|--------------------------------|---------|
      | `PATTERN`      | the task name pattern to match | `{{.INSTALL_DEFAULT_PATTERN}}` |

      Examples:
        - `task uninstall` will run all install tasks
        - `task {{.TASK}}` will explicitly run all install tasks
      
      Note:
        You can add any extra to all install commands by using "--". For example `task -- -f` to force all update.
    vars:
      PATTERN: '{{.PATTERN | default .UNINSTALL_DEFAULT_PATTERN}}'

    # this one-line is pretty scary
    cmds:
      - cmd: task -a --json | jq -c '[ (.tasks[] | select( .name | test({{.PATTERN | quote}})) | select( .name | index({{.TASK | quote}}) | not) ) | .name] | .[]' | xargs -n 1 -L1 -I'{}' sh -c 'task {} {{.CLI_ARGS}} || exit 255'
