version: '3'

vars:
  DEFAULT_GO_BIN: 'go'
  DEFAULT_GOLANGCI_PACKAGE: 'github.com/golangci/golangci-lint/v2/cmd/golangci-lint'
  DEFAULT_GOLANGCI_BIN_NAME: 'golangci-lint'
  DEFAULT_GOLANGCI_VERSION: 'latest'
  DEFAULT_GOLANGCI_GITHUBACTION_FILENAME: 'golangci.yml'
  DEFAULT_GOLANGCI_CONFIG_FILENAME: '.golangci.yaml'
  DEFAULT_GOLANGCI_SOURCES: '{{ .DEFAULT_GO_SOURCES | default "./..." }}'
  DEFAULT_GOLANGCI_ARGS: ''

tasks:
  default:
    cmds:
      - task: boilerplate
      - task: lint
      - task: ci

  pre-commit:
    cmd:
      task: default

  run:
    desc: Run golangci
    vars:
      BIN_NAME: '{{ .BIN_NAME | default .DEFAULT_GOLANGCI_BIN_NAME }}'
      GOLANGCI_ARGS: '{{ .GOLANGCI_ARGS | default .DEFAULT_GOLANGCI_ARGS }}'
    summary: |
      Run Golangci. The purpose is to have a reusable way to run Golangci.

      The following variables are available:

      | VARIABLE            | DESCRIPTION               | DEFAULT |
      |---------------------|---------------------------|---------|
      | `GOLANGCI_ARGS`     | golangci arguments        | `{{ .DEFAULT_GOLANGCI_ARGS }}` |
      | `BIN_NAME` | golangci bin name         | `{{ .DEFAULT_GOLANGCI_BIN_NAME }}` |

      Usual environment variables used for building a golang application are obviously available like:
        - `GOOS` for setting the build OS
        - `GOARCH` for setting the build architecture

      Extra arguments can be provided using `--` (non exclusive with `GOLANGCI_ARGS`).

      Examples:
        - `SOURCES=./cmd/... task {{ .TASK }}` is similar to `golangci-lint`
        - `task {{ .TASK }} -- -v` is similar to `golangci-lint -v`
        - `GOLANGCI_ARGS="-v" task {{ .TASK }}` is similar to `golangci-lint -v`

    cmd: 'go tool {{.BIN_NAME }} {{.GOLANGCI_ARGS}} {{.CLI_ARGS}}'

  install:
    vars:
      GO_BIN: '{{.GO_BIN | default .DEFAULT_GO_BIN}}'
      PACKAGE: '{{.PACKAGE | default .DEFAULT_GOLANGCI_PACKAGE}}'
      VERSION: '{{.VERSION | default .DEFAULT_GOLANGCI_VERSION}}'
    cmd: '{{.GO_BIN}} get -tool {{.PACKAGE}}@{{.VERSION}}'
    status:
      - go tool | grep {{.PACKAGE}}

  uninstall:
    vars:
      PACKAGE: '{{.PACKAGE | default .DEFAULT_GOLANGCI_PACKAGE}}'
      GO_BIN: '{{.GO_BIN | default .DEFAULT_GO_BIN}}'
    cmd: '{{.GO_BIN}} get -tool {{.PACKAGE}}@none'

  lint:
    desc: Lint golang source
    vars:
      SOURCES: '{{ .SOURCES | default .DEFAULT_GOLANGCI_SOURCES }}'
      CONFIG_FILENAME: '{{ .CONFIG_FILENAME | default .DEFAULT_GOLANGCI_CONFIG_FILENAME }}'
    summary: |
      Lint golang source using the standard golangci configuration.

      The following variables are available:

      | VARIABLE          | DESCRIPTION               | DEFAULT |
      |-------------------|---------------------------|---------|
      | `SOURCES`         | go sources of the project | `{{ .DEFAULT_GOLANGCI_SOURCES }}` |
      | `CONFIG_FILENAME` | config filename           | `{{ .DEFAULT_GOLANGCI_CONFIG_FILENAME }}` |

      Check `run` for more environments variables.

    cmds:
      - task: run
        vars:
          GOLANGCI_ARGS: 'run -c {{.CONFIG_FILENAME}} {{.CLI_ARGS}} {{.SOURCES}}'

  fix:
    desc: Fix golang source
    summary: |
      Fix golang source using the standard golangci configuration.
      Source may be fixed but it depends of the linter
      and may require further actions.
      
      Shortcut of `lint` task with `--fix`. Please refer to the `lint` task for details.
    cmds:
      - task: lint
        vars:
          CLI_ARGS: '--fix'

  ci:
    desc: Generate GitHub Action
    summary: |
      Generate a standardized golangci-lint GitHub Action configuration.
      This configuration is auto-generated and should not be manually modified as it can be overwritten.
      
      The generated file should be excluded from commits.
    vars:
      GITHUBACTION_FILENAME: '{{.ROOT_DIR}}/.github/workflows/{{.GITHUBACTION_FILENAME | default .DEFAULT_GOLANGCI_GITHUBACTION_FILENAME}}'
    cmds:
      - mkdir -p $(dirname "{{.GITHUBACTION_FILENAME}}")
      - echo "${GITHUBACTION_CONTENT}" > "{{.GITHUBACTION_FILENAME}}"
    status:
      - test -f '{{ .GITHUBACTION_FILENAME }}'
    env:
      GITHUBACTION_CONTENT: |
        # THIS FILE HAS BEEN GENERATED BY THE COMMAND `{{.TASK}}`; DO NOT EDIT;
        name: golangci-lint
        on:
          push:
            branches:
              - develop
              - main
              - master
          pull_request:
        
        permissions:
          contents: read
          # Optional: allow read access to pull request. Use with `only-new-issues` option.
          # pull-requests: read
        
        jobs:
          golangci:
            strategy:
              matrix:
                go: ['1.25']
                os: [macos-latest, ubuntu-latest]
            name: lint
            runs-on: ${{ "{{ matrix.os }}" }}
            steps:
              - uses: actions/checkout@v4
              - uses: actions/setup-go@v4
                with:
                  go-version: ${{ "{{ matrix.go }}" }}
                  cache: false
              - name: golangci-lint
                uses: golangci/golangci-lint-action@v8
                with:
                  # Require: The version of golangci-lint to use.
                  # When `install-mode` is `binary` (default) the value can be v1.2 or v1.2.3 or `latest` to use the latest version.
                  # When `install-mode` is `goinstall` the value can be v1.2.3, `latest`, or the hash of a commit.
                  version: latest
        
                  # Optional: working directory, useful for monorepos
                  # working-directory: somedir
        
                  # Optional: golangci-lint command line arguments.
                  #
                  # Note: by default the `.golangci.yml` file should be at the root of the repository.
                  # The location of the configuration file can be changed by using `--config=`
                  # args: --timeout=30m --config=/my/path/.golangci.yml --issues-exit-code=0
        
                  # Optional: show only new issues if it's a pull request. The default value is `false`.
                  # only-new-issues: true
        
                  # Optional:The mode to install golangci-lint. It can be 'binary' or 'goinstall'.
                  # install-mode: "goinstall"

  boilerplate:
    desc: Generate golang-ci configuration
    summary: |
      Generate golang-ci configuration.
      This configuration must be used as is and should not be modified.
      Any modification can be overwriting in the future.
      
      The generated file should be excluded from commits.
    vars:
      CONFIG_FILENAME: '{{.ROOT_DIR}}/{{.CONFIG_FILENAME | default .DEFAULT_GOLANGCI_CONFIG_FILENAME}}'
    cmds:
      - echo "${CONFIG_CONTENT}" > "{{.CONFIG_FILENAME}}"
    status:
      - test -f '{{ .CONFIG_FILENAME }}'
    env:
      CONFIG_CONTENT: |
        # THIS FILE HAS BEEN GENERATED BY THE COMMAND `{{.TASK}}`; DO NOT EDIT;
        version: "2"
        linters:
          default: none
          enable:
            - asasalint
            - asciicheck
            - bidichk
            - bodyclose
            - cyclop
            - dupl
            - durationcheck
            - errcheck
            - errname
            - errorlint
            - exhaustive
            - forbidigo
            - funlen
            - gocheckcompilerdirectives
            - gochecknoglobals
            - gochecknoinits
            - gocognit
            - goconst
            - gocritic
            - gocyclo
            - godot
            - gomoddirectives
            - gomodguard
            - goprintffuncname
            - gosec
            - govet
            - ineffassign
            - lll
            - loggercheck
            - makezero
            - musttag
            - nakedret
            - nestif
            - nilerr
            - nilnil
            - noctx
            - nolintlint
            - nonamedreturns
            - nosprintfhostport
            - predeclared
            - promlinter
            - reassign
            - revive
            - rowserrcheck
            - sqlclosecheck
            - staticcheck
            - testableexamples
            - testpackage
            - tparallel
            - unconvert
            - unparam
            - unused
            - usestdlibvars
            - wastedassign
            - whitespace
          settings:
            cyclop:
              max-complexity: 30
              package-average: 10
            errcheck:
              check-type-assertions: true
            exhaustive:
              check:
                - switch
                - map
            exhaustruct:
              exclude:
                - ^net/http.Client$
                - ^net/http.Cookie$
                - ^net/http.Request$
                - ^net/http.Response$
                - ^net/http.Server$
                - ^net/http.Transport$
                - ^net/url.URL$
                - ^os/exec.Cmd$
                - ^reflect.StructField$
                - ^github.com/Shopify/sarama.Config$
                - ^github.com/Shopify/sarama.ProducerMessage$
                - ^github.com/mitchellh/mapstructure.DecoderConfig$
                - ^github.com/prometheus/client_golang/.+Opts$
                - ^github.com/spf13/cobra.Command$
                - ^github.com/spf13/cobra.CompletionOptions$
                - ^github.com/stretchr/testify/mock.Mock$
                - ^github.com/testcontainers/testcontainers-go.+Request$
                - ^github.com/testcontainers/testcontainers-go.FromDockerfile$
                - ^golang.org/x/tools/go/analysis.Analyzer$
                - ^google.golang.org/protobuf/.+Options$
                - ^gopkg.in/yaml.v3.Node$
            funlen:
              lines: 100
              statements: 50
              ignore-comments: true
            gocognit:
              min-complexity: 40
            gocritic:
              settings:
                captLocal:
                  paramsOnly: false
                underef:
                  skipRecvDeref: false
            gomodguard:
              blocked:
                modules:
                  - github.com/golang/protobuf:
                      recommendations:
                        - google.golang.org/protobuf
                      reason: see https://developers.google.com/protocol-buffers/docs/reference/go/faq#modules
                  - github.com/satori/go.uuid:
                      recommendations:
                        - github.com/google/uuid
                      reason: satori's package is not maintained
                  - github.com/gofrs/uuid:
                      recommendations:
                        - github.com/google/uuid
                      reason: gofrs' package is not go module
            govet:
              disable:
                - fieldalignment
              enable-all: true
              settings:
                shadow:
                  strict: true
            nakedret:
              max-func-lines: 0
            nolintlint:
              require-explanation: true
              require-specific: true
              allow-no-explanation:
                - funlen
                - gocognit
                - lll
            rowserrcheck:
              packages:
                - github.com/jmoiron/sqlx
          exclusions:
            generated: lax
            presets:
              - comments
              - common-false-positives
              - legacy
              - std-error-handling
            rules:
              - linters:
                  - lll
                source: (help:")
              - linters:
                  - godot
                source: (noinspection|TODO)
              - linters:
                  - gocritic
                source: //noinspection
              - linters:
                  - bodyclose
                  - dupl
                  - funlen
                  - goconst
                  - gosec
                  - noctx
                  - wrapcheck
                path: _test\.go
            paths:
              - third_party$
              - builtin$
              - examples$
        issues:
          max-same-issues: 50
        formatters:
          enable:
            - goimports
          exclusions:
            generated: lax
            paths:
              - third_party$
              - builtin$
              - examples$